on:
  pull_request:
  push:
    branches:
      - main

jobs:
  terraform-plan:
    permissions:
      pull-requests: write
    uses: kir-dev/automations/.github/workflows/terraform-ci.yml@terraform-ci
    with:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}